/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superpuissance4_fontaine_royer;

import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author Hugo
 */
public class fenetredeJeu extends javax.swing.JFrame {
joueur Listejoueurs[] = new joueur[2];
joueur joueurCourant;
grille grilleDeJeu = new grille();
    /**
     * Creates new form fenetredeJeu
     */
    public fenetredeJeu() {
        initComponents();
        panneau_info_joueurs.setVisible(false);
        panneau_info_partie.setVisible(false);
        for (int i =5; i >=0; i--) {
            for (int j=0; j<7; j++) {
                CelluleGraphique cellGraph = new CelluleGraphique(grilleDeJeu.cellules[i][j]);
                cellGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellule c = cellGraph.celluleAssociee;
                if (c.CurrentToken == null) return;
                if (c.CurrentToken.PlayerColor.equals(joueurCourant.PlayerColor)) {
                    messagetext.setText("Le joueur "+joueurCourant.Nom+ "récupère un de ses jetons");
                    jeton jrecup = c.recupererJeton();
                    joueurCourant.ajouterJeton(jrecup);
                    joueurSuivant();
                }
                else {
                    if (joueurCourant.nombreDesintegrateurs > 0) {
                    messagetext.setText("Le joueur "+joueurCourant.Nom+ "désintègre un jeton");
                    c.supprimerJeton();
                    joueurCourant.utiliserDesintegrateur();
                    joueurSuivant();
                    }
                    else return;
                }
                grilleDeJeu.tasserGrille();
                panneau_grille.repaint();
                lbl_j1_desinte.setText(Listejoueurs[0].nombreDesintegrateurs+"");
        lbl_j2_desinte.setText(Listejoueurs[1].nombreDesintegrateurs+"");
        
        boolean vict_j1 = grilleDeJeu.etreGagnantePourJoueur(Listejoueurs[0]);
        boolean vict_j2 = grilleDeJeu.etreGagnantePourJoueur(Listejoueurs[1]);
        
        if (vict_j1 && ! vict_j2) messagetext.setText("Victoire de "+ Listejoueurs[0].Nom);
        if (vict_j2 && ! vict_j1) messagetext.setText("Victoire de "+ Listejoueurs[1].Nom);
        if (vict_j2 && vict_j1) {
            if (joueurCourant == Listejoueurs[0]) messagetext.setText("Victoire de "+ Listejoueurs[1].Nom+ "(faute de l'autre joueur)");
            else  messagetext.setText("Victoire de "+ Listejoueurs[0].Nom+"(faute de l'autre joueur)");
        }
            }
        });
                
                panneau_grille.add(cellGraph);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_grille = new javax.swing.JPanel();
        panneau_info_joueurs = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_j1_nom = new javax.swing.JLabel();
        lbl_j1_couleur = new javax.swing.JLabel();
        lbl_j1_desinte = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_j2_nom = new javax.swing.JLabel();
        lbl_j2_desinte = new javax.swing.JLabel();
        lbl_j2_couleur = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panneau_creation_partie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom_joueur1 = new javax.swing.JTextField();
        nom_joueur2 = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        panneau_info_partie = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_jcourant = new javax.swing.JLabel();
        message = new javax.swing.JScrollPane();
        messagetext = new javax.swing.JTextArea();
        ind_col_0 = new javax.swing.JButton();
        ind_col_3 = new javax.swing.JButton();
        ind_col_1 = new javax.swing.JButton();
        ind_col_2 = new javax.swing.JButton();
        ind_col_4 = new javax.swing.JButton();
        ind_col_5 = new javax.swing.JButton();
        ind_col_6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(255, 255, 255));
        panneau_grille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 672, 576));

        panneau_info_joueurs.setBackground(new java.awt.Color(255, 255, 255));
        panneau_info_joueurs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Information joueurs :");
        panneau_info_joueurs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        jLabel4.setText("Joueur1:");
        panneau_info_joueurs.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel5.setText("Couleur:");
        panneau_info_joueurs.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel6.setText("Désintégrateurs:");
        panneau_info_joueurs.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lbl_j1_nom.setText("nomJoueur1");
        panneau_info_joueurs.add(lbl_j1_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        lbl_j1_couleur.setText("couleurJoueur1");
        panneau_info_joueurs.add(lbl_j1_couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        lbl_j1_desinte.setText("nbDesintegrateur1");
        panneau_info_joueurs.add(lbl_j1_desinte, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel7.setText("Désintégrateurs:");
        panneau_info_joueurs.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel8.setText("Couleur:");
        panneau_info_joueurs.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel9.setText("Joueur2:");
        panneau_info_joueurs.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lbl_j2_nom.setText("nomJoueur2");
        panneau_info_joueurs.add(lbl_j2_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        lbl_j2_desinte.setText("nbDesintegrateur2");
        panneau_info_joueurs.add(lbl_j2_desinte, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        lbl_j2_couleur.setText("couleurJoueur2");
        panneau_info_joueurs.add(lbl_j2_couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        panneau_info_joueurs.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 230, 10));

        getContentPane().add(panneau_info_joueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 230, 230));

        panneau_creation_partie.setBackground(new java.awt.Color(255, 255, 255));
        panneau_creation_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom joueur 1 :");
        panneau_creation_partie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setText("Nom Joueur 2 :");
        panneau_creation_partie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        panneau_creation_partie.add(nom_joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, -1));

        nom_joueur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_joueur2ActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(nom_joueur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 50, -1));

        btn_start.setText("Démarrer Partie");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panneau_creation_partie.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        getContentPane().add(panneau_creation_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 240, 130));

        panneau_info_partie.setBackground(new java.awt.Color(255, 255, 255));
        panneau_info_partie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Information jeu:");
        panneau_info_partie.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 40));

        jLabel11.setText("joueur courant :");
        panneau_info_partie.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lbl_jcourant.setText("nomJoueur2");
        panneau_info_partie.add(lbl_jcourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        messagetext.setColumns(20);
        messagetext.setRows(5);
        message.setViewportView(messagetext);

        panneau_info_partie.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, -1));

        getContentPane().add(panneau_info_partie, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 230, 170));

        ind_col_0.setText("1");
        ind_col_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ind_col_0ActionPerformed(evt);
            }
        });
        getContentPane().add(ind_col_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        ind_col_3.setText("4");
        ind_col_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ind_col_3ActionPerformed(evt);
            }
        });
        getContentPane().add(ind_col_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 20, -1, -1));

        ind_col_1.setText("2");
        ind_col_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ind_col_1ActionPerformed(evt);
            }
        });
        getContentPane().add(ind_col_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 20, -1, -1));

        ind_col_2.setText("3");
        ind_col_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ind_col_2ActionPerformed(evt);
            }
        });
        getContentPane().add(ind_col_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 20, -1, -1));

        ind_col_4.setText("5");
        ind_col_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ind_col_4ActionPerformed(evt);
            }
        });
        getContentPane().add(ind_col_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        ind_col_5.setText("6");
        ind_col_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ind_col_5ActionPerformed(evt);
            }
        });
        getContentPane().add(ind_col_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        ind_col_6.setText("7");
        ind_col_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ind_col_6ActionPerformed(evt);
            }
        });
        getContentPane().add(ind_col_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 20, -1, -1));

        setBounds(0, 0, 1040, 698);
    }// </editor-fold>//GEN-END:initComponents

    private void nom_joueur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_joueur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_joueur2ActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        panneau_info_joueurs.setVisible(true);
        panneau_info_partie.setVisible(true);
        initialiserPartie();
        panneau_grille.repaint();
        btn_start.setEnabled(false);
    }//GEN-LAST:event_btn_startActionPerformed

    private void ind_col_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ind_col_2ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(2);
        if (grilleDeJeu.colonne_remplie(3)== true) ind_col_2.setEnabled(false);
        joueurSuivant();
    }//GEN-LAST:event_ind_col_2ActionPerformed

    private void ind_col_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ind_col_3ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(3);
        if (grilleDeJeu.colonne_remplie(1)== true) ind_col_3.setEnabled(false);
        joueurSuivant();
    }//GEN-LAST:event_ind_col_3ActionPerformed

    private void ind_col_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ind_col_6ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(6);
        if (grilleDeJeu.colonne_remplie(6)== true) ind_col_6.setEnabled(false);
        joueurSuivant();
    }//GEN-LAST:event_ind_col_6ActionPerformed

    private void ind_col_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ind_col_0ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(0);
        if (grilleDeJeu.colonne_remplie(0)== true) ind_col_0.setEnabled(false);
        joueurSuivant();
    }//GEN-LAST:event_ind_col_0ActionPerformed

    private void ind_col_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ind_col_1ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(1);
        if (grilleDeJeu.colonne_remplie(2)== true) ind_col_1.setEnabled(false);
        joueurSuivant();
    }//GEN-LAST:event_ind_col_1ActionPerformed

    private void ind_col_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ind_col_4ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(4);
        if (grilleDeJeu.colonne_remplie(4)== true) ind_col_4.setEnabled(false);
        joueurSuivant();
    }//GEN-LAST:event_ind_col_4ActionPerformed

    private void ind_col_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ind_col_5ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(5);
        if (grilleDeJeu.colonne_remplie(5)== true) ind_col_5.setEnabled(false);
        joueurSuivant();
    }//GEN-LAST:event_ind_col_5ActionPerformed
    
    public boolean jouerDansColonne(int indice_colonne) {
        boolean resultatAction;
        resultatAction = grilleDeJeu.ajouterJetonDansColonne(joueurCourant, indice_colonne);
        panneau_grille.repaint();
        lbl_j1_desinte.setText(Listejoueurs[0].nombreDesintegrateurs+"");
        lbl_j2_desinte.setText(Listejoueurs[1].nombreDesintegrateurs+"");
        
        boolean vict_j1 = grilleDeJeu.etreGagnantePourJoueur(Listejoueurs[0]);
        boolean vict_j2 = grilleDeJeu.etreGagnantePourJoueur(Listejoueurs[1]);
        
        if (vict_j1 && ! vict_j2) messagetext.setText("Victoire de "+ Listejoueurs[0].Nom);
        if (vict_j2 && ! vict_j1) messagetext.setText("Victoire de "+ Listejoueurs[1].Nom);
        if (vict_j2 && vict_j1) {
            if (joueurCourant == Listejoueurs[0]) messagetext.setText("Victoire de "+ Listejoueurs[1].Nom+ "(faute de l'autre joueur)");
            else  messagetext.setText("Victoire de "+ Listejoueurs[0].Nom+"(faute de l'autre joueur)");
        }
        
        
        if (resultatAction ==true) return true;
        else return false;
    }
    public void joueurSuivant(){
        if (joueurCourant == Listejoueurs[0]) {
            joueurCourant = Listejoueurs[1];
        }
        else {
            joueurCourant = Listejoueurs[0];
            lbl_jcourant.setText(joueurCourant.Nom);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetredeJeu().setVisible(true);
            }
        });
    }

 void initialiserPartie() {
        //Mise en place de la grille
        grilleDeJeu.viderGrille();

        //Création des joueur
        String nomJoueur1 = nom_joueur1.getText();
        joueur J1 = new joueur(nomJoueur1);
        String nomJoueur2 = nom_joueur2.getText();
        joueur J2 = new joueur(nomJoueur2);
        Listejoueurs[0] = J1;
        Listejoueurs[1] = J2;

        attribuerCouleursAuxJoueurs();

        System.out.println(J1.Nom + " est de couleur " + J1.PlayerColor);
        System.out.println(J2.Nom + " est de couleur " + J2.PlayerColor);

        lbl_j1_nom.setText(nomJoueur1);
        lbl_j2_nom.setText(nomJoueur2);
        lbl_j1_couleur.setText(J1.PlayerColor);
        lbl_j2_couleur.setText(J2.PlayerColor);
        lbl_j1_desinte.setText(J1.nombreDesintegrateurs+"");
        lbl_j2_desinte.setText(J2.nombreDesintegrateurs+"");
        // On donne des jetons aux joueurs
        for (int i = 0; i < 21; i++) {

            jeton J = new jeton(Listejoueurs[0].PlayerColor);

            J1.ajouterJeton(J);

            J2.ajouterJeton(new jeton(J2.PlayerColor));
        }

        // Determine qui est le premier joueur
        Random r = new Random();
        boolean le_premier = r.nextBoolean();
        if (le_premier) {
            joueurCourant = Listejoueurs[0];
        } else {
            joueurCourant = Listejoueurs[1];
        }
        lbl_jcourant.setText(joueurCourant.Nom);
        // Génération des 5 trous noirs et de 2 désintégrateurs sur les trou noirs
        int compteur = 0;
        for (int i = 0; i < 5; i++) {
            int ligne_trou_noir = r.nextInt(6);
            int colonne_trou_noir = r.nextInt(7);
            if (compteur < 2) {
                if (!grilleDeJeu.placerDesintegrateur(ligne_trou_noir, colonne_trou_noir)) {
                    compteur--;
                }
                compteur = compteur + 1;
            }
            if (!grilleDeJeu.placerTrouNoir(ligne_trou_noir, colonne_trou_noir)) {
                i--;
            }
        }

        // On place les trois derniers désintégrateurs
        for (int i = 0; i < 3; i++) {
            int ligne_désin = r.nextInt(6);
            int colonne_désin = r.nextInt(7);
            if (!grilleDeJeu.placerDesintegrateur(ligne_désin, colonne_désin) || grilleDeJeu.cellules[ligne_désin][colonne_désin].presenceTrouNoir()) {
                i--;
            }
        }

    }
    
 void attribuerCouleursAuxJoueurs() {
        Random r = new Random();
        boolean couleur;
        couleur = r.nextBoolean();
        if (couleur) {
            Listejoueurs[0].PlayerColor = "Rouge";
            Listejoueurs[1].PlayerColor = "Jaune";
        } else {
            Listejoueurs[0].PlayerColor = "Jaune";
            Listejoueurs[1].PlayerColor = "Rouge";
        }
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start;
    private javax.swing.JButton ind_col_0;
    private javax.swing.JButton ind_col_1;
    private javax.swing.JButton ind_col_2;
    private javax.swing.JButton ind_col_3;
    private javax.swing.JButton ind_col_4;
    private javax.swing.JButton ind_col_5;
    private javax.swing.JButton ind_col_6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_j1_couleur;
    private javax.swing.JLabel lbl_j1_desinte;
    private javax.swing.JLabel lbl_j1_nom;
    private javax.swing.JLabel lbl_j2_couleur;
    private javax.swing.JLabel lbl_j2_desinte;
    private javax.swing.JLabel lbl_j2_nom;
    private javax.swing.JLabel lbl_jcourant;
    private javax.swing.JScrollPane message;
    private javax.swing.JTextArea messagetext;
    private javax.swing.JTextField nom_joueur1;
    private javax.swing.JTextField nom_joueur2;
    private javax.swing.JPanel panneau_creation_partie;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_info_joueurs;
    private javax.swing.JPanel panneau_info_partie;
    // End of variables declaration//GEN-END:variables
}
